Repository ppc64le-cloud/packer-plugin-powervs, pull requests merged in 2025-01, with the labels that each got.

#261 user supplied subnet
  builder/powervs/builder.go
  builder/powervs/builder.hcl2spec.go
  builder/powervs/common/run_config.go
  builder/powervs/common/ssh.go
  builder/powervs/step_create_network.go
Labels: lgtm, approved, size/S

#263 Fix the sigsegv fault when image not found
  GNUmakefile
  builder/powervs/step_import_base_image.go
Labels: lgtm, approved

#266 Allow passing several subnets for vm creation
  builder/powervs/builder.go
  builder/powervs/builder.hcl2spec.go
  builder/powervs/common/run_config.go
  builder/powervs/step_create_instance.go
  builder/powervs/step_create_network.go
Labels: lgtm, approved, size/M

#271 introduce capture destination option
  builder/powervs/builder.go
  builder/powervs/common/run_config.go
  builder/powervs/common/run_config.hcl2spec.go
  builder/powervs/step_capture_instance.go
  docs-partials/builder/powervs/common/Capture-not-required.mdx
  docs-partials/builder/powervs/common/RunConfig-not-required.mdx
Labels: lgtm, approved, size/M
